modLoader = "javafml"
loaderVersion = "[52,)"
issueTrackerURL="${issues_url}"
license = "Apache"

[[mods]]
modId = "combatradar"
version = "${version}"
displayName = "CombatRadar"
authors = "Aleksey Terzi, MrJeremyFisher"
description = '''
'''
logoFile = "icon.png"

[[dependencies.combatradar]]
modId = "forge"
mandatory = true
versionRange = "[52,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.combatradar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "CLIENT"