modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL="${issues_url}"
license = "Apache"

[[mods]]
modId = "combatradar"
version = "${version}"
displayName = "CombatRadar"
authors = "Aleksey Terzi, MrJeremyFisher"
description = '''
Radar that helps you find mobs and players.
'''
logoFile = "icon.png"

[[dependencies.combatradar]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.combatradar]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"