org.gradle.jvmargs=-Xmx4G

minecraft_version=26.2
# TODO: reenable forge when architectury no longer broken
enabled_platforms=fabric,neoforge

archives_base_name=combatradar
mod_version=1.7.11-mc26.2
maven_group=com.aleksey.combatradar

# Update from https://parchmentmc.org/docs/getting-started or the ParchmentMC discord
parchment_version=2025.12.20

# Update from https://fabricmc.net/develop/
fabric_loader_version=0.19.3
fabric_api_version=0.152.1+26.2

# Update from https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=64.0.0

# Update from https://neoforged.net/
neoforge_version=26.2.0.1-beta

# Update from https://modrinth.com/mod/modmenu/versions
modmenu_version=20.0.0-beta.2

issues_url=https://github.com/MrJeremyFisher/CombatRadar/issues