modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "${issues_url}"
license = "Apache"

[[mods]]
modId = "combatradar"
version = "${version}"
displayName = "CombatRadar"
authors = "Aleksey Terzi, MrJeremyFisher"
description = '''
Radar that helps you find mobs and players.
'''
logoFile = "icon.png"

[[mixins]]
config = "combatradar.neoforge.mixins.json"

[[dependencies.combatradar]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.combatradar]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"